version: '3.8'

services:
  app:
    image: node:20
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    command: sh -c "npm install && npx ts-node && npx ts-node src/server.ts"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
